### ISSUE TITLE
Warning: cassandra20-2.0.14-1.noarch.rpm is not signed

### ISSUE THREAD

**Issue by igarny** [perfsonar/toolkit#59] opened 2015-08-05 08:26 UTC
Hi,

Here is the output of the install attempt

Error: Execution of '/usr/bin/yum -d 0 -e 0 -y install perl-perfSONAR_PS-Toolkit' returned 1:

Package cassandra20-2.0.14-1.noarch.rpm is not signed

we are using this KEY: http://software.internet2.edu/rpms/RPM-GPG-KEY-Internet2

Best regards,
Ivan

**Comment by arlake228** [comment] 2015-08-05 12:23
Can you send the full output of "yum install cassandra20"? I'm curious what mirror and repo you are using since it appears to be signed in the Internet2 repo.

**Comment by apertome** [comment] 2015-12-03 15:04
I'm guessing this has been addressed?

**Comment by arlake228** [comment] 2016-02-09 15:38
Have not been able to reproduce for many months so closing.

**Closed by arlake228** 2016-02-09 15:38 UTC
