### ISSUE TITLE
Ubuntu 20 reverse ping test permissions

### ISSUE THREAD

**Issue by ngacesa** [perfsonar/toolkit#441] opened 2023-09-28 11:50 UTC
It seems by default, Ubuntu 20.04 does not permit non-root users to issue ping commands, even after being added to sudoers. As a result, if using a non-root user for the toolkit web interface (which most people will do), the reverse-ping test will fail with a permission warning. Unfortunately I didn't save a screenshot before fixing the problem, but I suggest modifying the install script for the toolkit to allow non-root user this privilege.

This worked for me: `setcap 'cap_net_admin,cap_net_raw+ep' /usr/bin/ping`

Best,
Nikola, GEANT PMP Team
@tonin

**Comment by arlake228** [comment] 2023-09-28 13:58
Thanks for the report. This is a caused by same issue as perfsonar/pscheduler#1350. Fix has been implemented and will be released with 5.0.5 which should be available in the next 24 hours or so.

**Closed by arlake228** 2023-09-28 13:58 UTC
