### ISSUE TITLE
Auto Updates toggle state does not persist after save on CentOS 7 host

### ISSUE THREAD

**Issue by somedatapacket** [perfsonar/toolkit#175] opened 2016-12-06 21:16 UTC
In /toolkit/auth/admin/host.cgi, toggling Auto Updates to "enabled" and saving the configuration does not enable Auto Updates. The toggle reverts to "disabled" on save.

**Comment by apertome** [comment] 2016-12-22 20:32
I confirmed this on CentOS 7.  I see stuff like this in `/var/log/httpd/ssl_error_log`:

> [Thu Dec 22 15:28:48.481093 2016] [cgi:error] [pid 3234] [client 129.79.9.117:54140] AH01215: Use of uninitialized value $result in index at /usr/lib/perfsonar/web-ng/root/admin/services/../../../../lib/perfSONAR_PS/Utils/Host.pm line 718., referer: https://129.79.9.73/toolkit/auth/admin/
> [Thu Dec 22 15:30:09.473320 2016] [cgi:error] [pid 4429] [client 129.79.9.117:54364] AH01215: Can't exec "/etc/init.d/yum-cron": No such file or directory at /usr/lib/perfsonar/web-ng/root/admin/services/../../../../lib/perfSONAR_PS/Utils/Host.pm line 716., referer: https://129.79.9.73/toolkit/auth/admin/host.cgi

We'll need to update the code that handles this for CentOS 7.

**Comment by apertome** [comment] 2017-01-05 21:34
This should be fixed; I would push it to the nightly repo, but that repo is still down. @somedatapacket perhaps you can double-check this once we get things running again?

**Comment by apertome** [comment] 2017-01-06 15:31
This has been built and is in the process of being pushed to the repo. It should be available for testing later today.

**Comment by somedatapacket** [comment] 2017-02-08 18:10
@apertome there are still page load issues with the GUI in 4.0 on CentOS 7 for the u-m host at least. The auto-update toggle state now persists on save, but on reload, it reverts to the "disabled" state.

**Comment by apertome** [comment] 2017-02-09 14:46
@somedatapacket I'll look at it again, thanks for the update

**Comment by apertome** [comment] 2017-02-09 19:13
Is your host using the nightly repo, or staging?

**Comment by apertome** [comment] 2017-02-09 19:24
I can't reproduce this, I have tried on two hosts. Are there any errors in these files when you try to save?

`/var/log/httpd/ssl_error_log`
`/var/log/perfsonar/web_admin/web_admin.log`
`/var/log/perfsonar/configdaemon.log`

**Comment by somedatapacket** [comment] 2017-02-09 20:20
@apertome nightly repo. 2017/02/09 15:19:44 (2418) ERROR> ConfigDaemon.pm:245 perfSONAR_PS::NPToolkit::ConfigManager::ConfigDaemon::startService - Enabling yum_cron in startup

**Comment by somedatapacket** [comment] 2017-02-09 21:32
SELinux was enabled. Disabling causes the web UI to behave as expected.

**Comment by apertome** [comment] 2017-02-09 21:48
Since this was a host issue, closing this again.

**Closed by apertome** 2017-02-09 21:48 UTC
Labels: bug
