### ISSUE TITLE
Community browsing and selecting dialogs not available in Toolkit GUI

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#335] opened 2018-09-25 20:50 UTC
In the current version of toolkit GUI something is broken and community browsing is impossible:
- in Administrative Information tab trying to add new community do not open a list of available communities. It just prints No results found
- when adding new test and searching host by community clicking on the link browse communities again displays red message No communities found

Tested with:
pS 4.1.2 with CentOS7 with FF and Edge browsers. 
Confirmed with 4.0 (CenOS6) where it is working properly.

It may be related to #333 but I'm not sure.

**Comment by apertome** [comment] 2018-09-26 16:48
This works ok on my host, will try to reproduce

**Comment by apertome** [comment] 2018-09-26 16:49
Is this on a clean install of 4.1?

**Comment by szymontrocha** [comment] 2018-09-26 16:57
yes, check e.g. this one http://145.100.181.3/toolkit/  This was a clean host now it's after workshop
I'm using FF ESR 52.9
Also broken on iOS 12 :-)

**Comment by apertome** [comment] 2018-09-27 15:09
Do you see anything in
/var/lib/perfsonar/lscache/

on the host?

**Comment by szymontrocha** [comment] 2018-09-27 16:05
It's empty

**Comment by apertome** [comment] 2018-09-27 21:19
It looks like the URL the ls cache daemon uses to retrieve the list of LSes is returning a 302 redirect to the SSL version of the same file, which the daemon is not following. So new hosts will never get the LS data.

**Comment by apertome** [comment] 2018-10-01 19:28
I sent out a note to the dev list about this a few days ago; no responses yet, so I just sent a ping.

**Comment by apertome** [comment] 2018-10-12 15:08
This is fixed and will be included in 4.1.3

This turned out to be a missing dependency on CentOS 7, `perl-LWP-Protocol-https`

Not sure if there is a similar dependency needed in Debian land

**Comment by tonin** [comment] 2018-10-12 15:14
@vvidic Can you double check if a fresh Debian toolkit install is exhibiting the same behavior and also needs a fix?

**Comment by apertome** [comment] 2018-10-12 15:46
The behavior is quite subtle, in that the problem is that without this library the ls cache daemon cannot follow a redirect to an https URL. Since the production ls hints url no longer redirects to https, this could be tricky to reproduce.

This might help -- I made a fake ls cache hints file that does redirect to https. If you put this in lscachedaemon.conf you should be able to see if the redirect works or not.

http://mj-dev.grnoc.iu.edu/test/ls.cache.hints

**Comment by vvidic** [comment] 2018-10-12 16:05
In Debian `libwww-perl` depends on `liblwp-protocol-https-perl`, so HTTPS should work but I will double check.

**Comment by vvidic** [comment] 2018-10-15 11:30
Looks good on Debian and Ubuntu side: `liblwp-protocol-https-perl` is always installed and http://mj-dev.grnoc.iu.edu/test/ls.cache.hints works fine in `lscachedaemon.conf`:

``
ts=2018-10-15T11:26:42.108843Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.handle.start guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:42.108982Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.cond_get.start url=http://mj-dev.grnoc.iu.edu/test/ls.cache.hints guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:42.913781Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.cond_get.end http_response_code=200 url=http://mj-dev.grnoc.iu.edu/test/ls.cache.hints guid=c4d77edf-036d-45d9-8607-e96e209a90d4
heartbeat_url=http://ps-east.es.net/ls_cache_heartbeat.txt
ts=2018-10-15T11:26:43.142561Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.cond_get.start url=http://ps-east.es.net/ls_cache_heartbeat.txt guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:43.349532Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.cond_get.end http_response_code=200 url=http://ps-east.es.net/ls_cache_heartbeat.txt guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:43.350727Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.cond_get.start url=http://ps-east.es.net/cache.tgz guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:44.179559Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.cond_get.end http_response_code=200 url=http://ps-east.es.net/cache.tgz guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:44.201809Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.archive_file.start guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:44.202051Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.archive_file.end guid=c4d77edf-036d-45d9-8607-e96e209a90d4
ts=2018-10-15T11:26:44.202181Z event=org.perfSONAR.LSCacheDaemon.LSCacheHandler.handle.end next_update=1539631604 msg= guid=c4d77edf-036d-45d9-8607-e96e209a90d4
``

**Comment by apertome** [comment] 2018-10-15 13:40
Thanks, @vvidic !

**Closed by apertome** 2018-10-15 13:40 UTC
Labels: bug
