### ISSUE TITLE
Make keys in Toolkit JSON summary static

### ISSUE THREAD

**Issue by arlake228** [perfsonar/toolkit#303] opened 2018-03-12 15:11 UTC
WLCG pointed out that it is made more difficult for them to store JSON in ElasticSearch because some keys are "dynamic" in the sense that they are keyed by the interface name or similar. They would prefer instead it was a list of objects with fields like "ifName" that are fixed. We can contact Marian Babik for more information on the type of transforms they have to do to identify paint points.

**Comment by apertome** [comment] 2018-10-24 16:52
This is a dupe of #248; closing

**Closed by apertome** 2018-10-24 16:52 UTC
Labels: duplicate, f2f-meeting-outcome
