### ISSUE TITLE
Enable NTP by default at first install

### ISSUE THREAD

**Issue by szymontrocha** [perfsonar/toolkit#162] opened 2016-11-03 14:45 UTC
After a fresh installation of ISO toolkit ntpd is not started immediately by default. You have to go to web and modify NTP settings to force ntpd daemon running (or start manually).
By default toolkit already comes with a list of close NTP servers which are loaded and appear in gui. So I don't see a conflict with running the daemon immediately. And then administrator improves ntp by selecting other servers if necessary.

**Comment by arlake228** [comment] 2016-11-10 15:13
I think this is a duplicate of #163 so merging

**Closed by arlake228** 2016-11-10 15:13 UTC
Labels: enhancement
